name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ubuntu-gcc:
    runs-on: ubuntu-24.04
    env:
      CC: gcc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Show versions
        run: |
          $CC --version
          make --version

      - name: Run unittest
        run: |
          set -euxo pipefail
          make unittest

      - name: Run warntest
        if: ${{ always() }}
        run: |
          set -euxo pipefail
          make warntest
